#! /usr/bin/sage -python
# -*- coding: utf8 -*-

from phystricks import *
import sys

from phystricksITZAPPh import ITZAPPh
from phystricksXSMDwcv import XSMDwcv
from phystricksIQnEPpt import IQnEPpt
from phystricksYVZAXhU import YVZAXhU
from phystricksJRVlexw import JRVlexw
from phystricksGCxOEgb import GCxOEgb
from phystricksJHrkjFz import JHrkjFz
from phystricksBIlgjwy import BIlgjwy
from phystricksLOBVHYF import LOBVHYF
from phystricksYORfWSM import YORfWSM
from phystricksVMNerGf import VMNerGf
from phystricksTOcdZDG import TOcdZDG
from phystricksOHfdEZt import OHfdEZt
from phystricksYAaXJqQ import YAaXJqQ
from phystricksfigureWYxZPMW import figureWYxZPMW
from phystricksfigureCFoZCYe import figureCFoZCYe
from phystricksfigureSNpNWPt import figureSNpNWPt
from phystricksfigureZEKOYck import figureZEKOYck
from phystricksfigureMIdFCNN import figureMIdFCNN
from phystricksfigureSIZwqIZ import figureSIZwqIZ
from phystricksfigureEHyIMRQ import figureEHyIMRQ
from phystricksfigureKAzSlQr import figureKAzSlQr
from phystricksfigureSZyxsvp import figureSZyxsvp
from phystricksfigureXCScSiP import figureXCScSiP
from phystricksfigureHYeBZVj import figureHYeBZVj
from phystricksKKEdcAR import KKEdcAR
from phystricksfigureFGgTGJA import figureFGgTGJA
from phystricksfigureHFdjZpb import figureHFdjZpb
from phystricksfigureISQqBVu import figureISQqBVu
from phystricksfigurePQKzIRY import figurePQKzIRY
from phystricksfigureMYeLqLl import figureMYeLqLl
from phystricksfigureDTzvwiz import figureDTzvwiz
from phystricksfigureTJkpHLv import figureTJkpHLv
from phystricksfigureEWDVDTS import figureEWDVDTS
from phystricksfigureXNAufCh import figureXNAufCh
from phystricksfigureQUtOjcm import figureQUtOjcm
from phystricksfigureXUQaJjF import figureXUQaJjF
from phystricksfigureUERGVgS import figureUERGVgS
from phystricksfigureSCkAAJI import figureSCkAAJI
from phystricksfigureBOuQJyj import figureBOuQJyj
from phystricksfigureVNaHvXi import figureVNaHvXi
from phystricksfigureLEOvqez import figureLEOvqez
from phystricksfigureFNkqWFE import figureFNkqWFE
from phystricksfigureNNgEEzx import figureNNgEEzx
from phystricksfigureXQZwoWu import figureXQZwoWu
from phystricksfigureKHUxoaG import figureKHUxoaG
from phystricksfigureYWEhCkv import figureYWEhCkv
from phystricksJOKJMTD import JOKJMTD
from phystricksfigureWFDTzSN import figureWFDTzSN
from phystricksfigureNPQwFTp import figureNPQwFTp
from phystricksfigureERITfSy import figureERITfSy
from phystricksfigureBCtCTZo import figureBCtCTZo
from phystricksPositionPlansqSltxa import PositionPlansqSltxa
from phystricksPositionPlansTvKvah import PositionPlansTvKvah
from phystricksPositionRelativexpwkEJ import PositionRelativexpwkEJ
from phystricksExoTrigTrIpPW import ExoTrigTrIpPW
from phystricksExoVectoFRPXxB import ExoVectoFRPXxB
from phystricksTracerUn import TracerUn
from phystricksExerciceGraphes import ExerciceGraphes
from phystricksExerciceGraphesbis import ExerciceGraphesbis
from phystricksGrapheunsurunmoinsx import Grapheunsurunmoinsx
from phystricksExoCUd import ExoCUd
from phystricksUnSurxInt import UnSurxInt
from phystricksAireParabole import AireParabole
from phystricksPartieEntiere import PartieEntiere
from phystricksMantisse import Mantisse
from phystricksDS2010ExoGraph import DS2010ExoGraph
from phystricksDS2010bisExoGraph import DS2010bisExoGraph
from phystricksSolsEqDiffSin import SolsEqDiffSin
from phystricksSolsSinpA import SolsSinpA
from phystricksTrajs import Trajs

from phystricksEvZZys import EvZZys
from phystricksBpCNVm import BpCNVm
#from phystricksNotesSVT import NotesSVT
from phystricksHistoAutomobile import HistoAutomobile
from phystricksHistoTdkccB import HistoTdkccB
from phystricksHistoPySeT import HistoPySeT
from phystricksHistoAgeFrance import HistoAgeFrance
from phystricksHistoAgeKenya import HistoAgeKenya
from phystricksSecondDeg import SecondDeg
from phystricksParabolesfTKFw import ParabolesfTKFw
from phystricksEffectifsCumulwfqAhj import EffectifsCumulwfqAhj
from phystricksSurfaceTriangletcNPPE import SurfaceTriangletcNPPE
from phystricksLectureGraphnrkEEM import LectureGraphnrkEEM
from phystricksParaboleMCLCbG import ParaboleMCLCbG
from phystricksbDdpfh import bDdpfh
from phystricksParabolevQzhjq import ParabolevQzhjq
from phystricksParaboleiLbviP import ParaboleiLbviP
from phystricksParaboleHautMLbPQF import ParaboleHautMLbPQF
from phystricksParaboleBasfKtFCN import ParaboleBasfKtFCN
from phystricksParabolezBeHFl import ParabolezBeHFl
from phystricksParabolezmMGdN import ParabolezmMGdN
from phystricksParaboleUneSolPktmCR import ParaboleUneSolPktmCR
from phystricksParaboleHautjOEAzn import ParaboleHautjOEAzn
from phystricksParaboleBasDqAAua import ParaboleBasDqAAua
from phystricksParaboleUniqueHautviflbY import ParaboleUniqueHautviflbY
from phystricksParaboleUniqueBaskGdqda import ParaboleUniqueBaskGdqda
from phystricksMathCeilwCXIJZ import MathCeilwCXIJZ
from phystricksReperexjVyii import ReperexjVyii
from phystricksPythagoreeBqLDU import PythagoreeBqLDU
from phystricksParaboleoytUKk import ParaboleoytUKk
from phystricksParabolesoDGyNW import ParabolesoDGyNW
from phystricksExGrapheOcxXii import ExGrapheOcxXii
from phystricksPasFonctionYoQfSu import PasFonctionYoQfSu
from phystricksGrapheAffinHqXJGx import GrapheAffinHqXJGx
from phystricksExoIntersectionCourbenzIxXd import ExoIntersectionCourbenzIxXd
from phystricksFCarreQFhsWz import FCarreQFhsWz
from phystricksExCarrexvfvre import ExCarrexvfvre
from phystricksExResolutionOSiaMS import ExResolutionOSiaMS
from phystricksExEquationIntersectioniSHPTw import ExEquationIntersectioniSHPTw
from phystricksExIneqOcAWMq import ExIneqOcAWMq
from phystricksExIneqfgZWStde import ExIneqfgZWStde
from phystricksExVariationRXTkoc import ExVariationRXTkoc
from phystricksExoGraphIneqPgErDr import ExoGraphIneqPgErDr
from phystricksExVarGraphiqueyhHpqn import ExVarGraphiqueyhHpqn
from phystricksGrapheVarndvdQM import GrapheVarndvdQM
from phystricksFoncConstFdDkhW import FoncConstFdDkhW
from phystricksGrapheVarREGMqx import GrapheVarREGMqx
from phystricksFnAffineipcEQf import FnAffineipcEQf
from phystricksMinMaxKNRdOd import MinMaxKNRdOd
from phystricksCubeLFZuiW import CubeLFZuiW
from phystricksDesSectionseVPNeL import DesSectionseVPNeL
from phystricksIllusionNHwEtp import IllusionNHwEtp
from phystricksLignesCubeshBfjxk import LignesCubeshBfjxk
from phystricksSurfacesCubesclGZD import SurfacesCubesclGZD
from phystricksCylindresxKDOdy import CylindresxKDOdy
from phystricksFaussePerspectivewAwxAJ import FaussePerspectivewAwxAJ
from phystricksCubeLigneTriangleHFMrVU import CubeLigneTriangleHFMrVU
from phystricksSurfaceCubeXlLEEy import SurfaceCubeXlLEEy
from phystricksDansRectangleGPEkJc import DansRectangleGPEkJc
from phystricksPrismeCQlZKY import PrismeCQlZKY
from phystricksIsoceleVdviOE import IsoceleVdviOE
from phystricksPerpSegqrbMBZ import PerpSegqrbMBZ
from phystricksPositionsDroitesbnYIsH import PositionsDroitesbnYIsH
from phystricksCorSSTXPQVjn import CorSSTXPQVjn
from phystricksGraphInterfQVfSf import GraphInterfQVfSf
from phystricksParaboleResumeHNiyfR import ParaboleResumeHNiyfR
from phystricksParaboleResumeSzaWaG import ParaboleResumeSzaWaG
from phystricksSimulBinNWxfTN import SimulBinNWxfTN
from phystricksFnInterrobgepC import FnInterrobgepC
from phystricksRouletteACaVAA import RouletteACaVAA
from phystricksPetiteBinomialelzbdWl import PetiteBinomialelzbdWl
from phystricksGrandeBinomialeIyWAIh import GrandeBinomialeIyWAIh
from phystricksExoBinomialeNyQLYI import ExoBinomialeNyQLYI
from phystricksRectanglegHuBZs import RectanglegHuBZs
from phystricksThaleszlOKVq import ThaleszlOKVq
from phystricksExoTranslationPNjoHk import ExoTranslationPNjoHk
from phystricksDefVecteurAXDDGP import DefVecteurAXDDGP
from phystricksVectoParallItzteT import VectoParallItzteT
from phystricksVectoParallelgjDlmD import VectoParallelgjDlmD
from phystricksChaslesGTRtKR import ChaslesGTRtKR
from phystricksVectoMilieuNuWgHW import VectoMilieuNuWgHW
from phystricksExoVectoPJGrRF import ExoVectoPJGrRF
from phystricksfigureASkECWS import figureASkECWS
from phystricksfigureCSIQETx import figureCSIQETx
from phystricksfigureTFaRFVd import figureTFaRFVd
from phystricksfigureITVTofz import figureITVTofz
from phystricksfigureNAKnjxQ import figureNAKnjxQ
from phystricksfigureAEcZqpP import figureAEcZqpP

def AllFigures(figures_list):
    tests=main.FigureGenerationSuite(figures_list,first=0,title=u"Soupçon de mathématiques")
    tests.generate()
    tests.summary()

figures_list=[DS2010bisExoGraph, ExoCUd,DS2010ExoGraph,SolsEqDiffSin, Grapheunsurunmoinsx, TracerUn, ExerciceGraphes,SolsSinpA,Trajs, ExerciceGraphesbis,
    UnSurxInt, AireParabole, PartieEntiere, Mantisse, EvZZys,BpCNVm,HistoAutomobile,HistoTdkccB,HistoPySeT, HistoAgeFrance,HistoAgeKenya,
    EffectifsCumulwfqAhj,SurfaceTriangletcNPPE,ParabolevQzhjq,bDdpfh,ParaboleiLbviP,ParaboleMCLCbG,ParaboleHautMLbPQF,
    ParaboleBasfKtFCN,ParabolezBeHFl,ParabolezmMGdN,ParaboleUneSolPktmCR,ParaboleHautjOEAzn,ParaboleBasDqAAua,ParaboleUniqueHautviflbY,
    ParaboleUniqueBaskGdqda, MathCeilwCXIJZ,ReperexjVyii,PythagoreeBqLDU,ParaboleoytUKk,ParabolesoDGyNW,SecondDeg,ExGrapheOcxXii,
    GrapheAffinHqXJGx,ExoIntersectionCourbenzIxXd,FCarreQFhsWz,ExCarrexvfvre,ExResolutionOSiaMS,ExEquationIntersectioniSHPTw,ExIneqOcAWMq,
    ExIneqfgZWStde,ExVariationRXTkoc,ExoGraphIneqPgErDr,ExVarGraphiqueyhHpqn,GrapheVarndvdQM,FoncConstFdDkhW,GrapheVarREGMqx,FnAffineipcEQf,MinMaxKNRdOd,
    ParabolesfTKFw,CubeLFZuiW,DesSectionseVPNeL,LectureGraphnrkEEM,PasFonctionYoQfSu,IllusionNHwEtp,LignesCubeshBfjxk,SurfacesCubesclGZD,
    FaussePerspectivewAwxAJ,CubeLigneTriangleHFMrVU,SurfaceCubeXlLEEy,DansRectangleGPEkJc,PrismeCQlZKY,IsoceleVdviOE,PerpSegqrbMBZ,PositionsDroitesbnYIsH,
    CorSSTXPQVjn,GraphInterfQVfSf,ParaboleResumeHNiyfR,ParaboleResumeSzaWaG,SimulBinNWxfTN,FnInterrobgepC,RouletteACaVAA,PetiteBinomialelzbdWl,GrandeBinomialeIyWAIh,
    ExoBinomialeNyQLYI,RectanglegHuBZs,ThaleszlOKVq,DefVecteurAXDDGP,VectoParallItzteT,VectoParallelgjDlmD,ChaslesGTRtKR,VectoMilieuNuWgHW,
    ExoVectoFRPXxB,ExoVectoPJGrRF,ExoTrigTrIpPW,PositionRelativexpwkEJ,PositionPlansTvKvah,PositionPlansqSltxa,figureBCtCTZo,figureASkECWS,figureCSIQETx,figureTFaRFVd,
    figureERITfSy,figureNPQwFTp,figureITVTofz,figureNAKnjxQ,figureWFDTzSN,JOKJMTD,figureYWEhCkv,figureAEcZqpP,ExoTranslationPNjoHk,figureKHUxoaG,figureXQZwoWu,
    CylindresxKDOdy, figureNNgEEzx,figureFNkqWFE,figureLEOvqez,figureVNaHvXi,figureBOuQJyj,figureSCkAAJI,figureUERGVgS,figureXUQaJjF,figureQUtOjcm,figureXNAufCh,
    figureEWDVDTS, figureTJkpHLv,figureDTzvwiz,figureMYeLqLl,figurePQKzIRY,figureISQqBVu,figureHFdjZpb,figureFGgTGJA,KKEdcAR,figureXCScSiP, figureSZyxsvp,
    figureHYeBZVj,figureKAzSlQr,figureEHyIMRQ,figureSIZwqIZ,figureMIdFCNN,figureZEKOYck,figureSNpNWPt,figureCFoZCYe,figureWYxZPMW,YAaXJqQ,OHfdEZt,TOcdZDG,VMNerGf,YORfWSM,
    LOBVHYF,BIlgjwy,JHrkjFz,GCxOEgb,JRVlexw,YVZAXhU,IQnEPpt,XSMDwcv,ITZAPPh
    ]


for k in sys.argv:
    s=[]
    fun=k.replace("phystricks","").replace(".py","")
    print fun
    if fun in globals().keys():
        print "ok"
        s.append(globals()[fun])

if s:
    figures_list=s

if __name__=="__main__":
    if "--all" not in sys.argv :
        figures_list=figures_list[-1:]

    AllFigures(figures_list)
